---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero
  client_rb:
    environment: 'stage'

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[stale-node-checker::default]
    attributes:
      postfix:
        aliases:
          root: devops@evertrue.com
